- name: Installer Nginx dans un conteneur Docker
  hosts: docker
  become: yes
  tasks:
    - name: Mettre à jour les paquets APT
      apt:
        update_cache: yes

    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: S'assurer que Nginx est démarré
      service:
        name: nginx
        state: started
